global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'central-monitoring'

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  # Scrape Alloy agents (for monitoring the agents themselves)
  - job_name: 'alloy-dev-db'
    static_configs:
      - targets: ['10.20.10.10:12345']
        labels:
          environment: 'dev'
          vm_type: 'database'
          instance: 'dev-db'

  # Scrape Alloy agents (for monitoring the agents themselves)
  - job_name: 'alloy-dev-back'
    static_configs:
      - targets: ['10.20.10.11:12345']
        labels:
          environment: 'dev'
          vm_type: 'backend'
          instance: 'dev-back'
  # Scrape Alloy agents (for monitoring the agents themselves)
  - job_name: 'alloy-dev-front'
    static_configs:
      - targets: ['10.20.10.12:12345']
        labels:
          environment: 'dev'
          vm_type: 'frontend'
          instance: 'dev-front'
  # Scrape Alloy agents (for monitoring the agents themselves)
  - job_name: 'alloy-qa-db'
    static_configs:
      - targets: ['10.20.20.10:12345']
        labels:
          environment: 'qa'
          vm_type: 'database'
          instance: 'qa-db'
  # Scrape Alloy agents (for monitoring the agents themselves)
  - job_name: 'alloy-qa-back'
    static_configs:
      - targets: ['10.20.20.11:12345']
        labels:
          environment: 'qa'
          vm_type: 'backend'
          instance: 'qa-back'
