server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape all Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.dokku.app-name"]  # Only Dokku apps
    relabel_configs:
      # Extract Dokku app name
      - source_labels: ['__meta_docker_container_label_com_dokku_app_name']
        target_label: 'app'
      # Extract container name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Extract process type (web, worker, etc.)
      - source_labels: ['__meta_docker_container_label_com_dokku_process_type']
        target_label: 'process_type'
      # Log stream (stdout/stderr)
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

  # Alternative: Scrape ALL containers (if you want logs from everything)
  - job_name: all_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
