{
 "title": "Frontend Dev",
 "description": "La maquina virtual de frontend en el entorno de desarrollo",
 "tags": [
  "DEV",
  "FRONT"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Uso de memoria en %",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes{environment=\"dev\", vm_type=\"frontend\"} / node_memory_MemTotal_bytes{environment=\"dev\", vm_type=\"frontend\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Uso del CPU en %",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", environment=\"dev\", vm_type=\"frontend\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "- **Load < CPU cores** = System has spare capacity ✅\n- **Load = CPU cores** = System is fully utilized ⚠️\n- **Load > CPU cores** = System is overloaded 🔴",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{environment=\"dev\", vm_type=\"frontend\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_load5{environment=\"dev\", vm_type=\"frontend\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "node_load15{environment=\"dev\", vm_type=\"frontend\"}",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "vector(8)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network traffic RX",
   "type": "timeseries",
   "description": "Trafico de red recibido",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{environment=\"dev\", vm_type=\"frontend\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network traffic TX",
   "type": "timeseries",
   "description": "Trafico de red Transmitido",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{environment=\"dev\", vm_type=\"frontend\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Uso del disco",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{environment=\"dev\", vm_type=\"frontend\", mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{environment=\"dev\", vm_type=\"frontend\", mountpoint=\"/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "{environment=\"dev\", vm_type=\"frontend\"}"
    }
   ]
  },
  {
   "title": "Container Memory usage (TOP 5)",
   "type": "timeseries",
   "description": "Top 5 Contenedores por uso de memoria",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(5, sum by (name) (container_memory_usage_bytes{environment=\"dev\", vm_type=\"frontend\", name!=\"\"}) / 1024 / 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU usage (TOP 5)",
   "type": "timeseries",
   "description": "Uso del CPU de containers (los 5 mas costosos)",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "topk(5, sum by (name) (rate(container_cpu_usage_seconds_total{environment=\"dev\", vm_type=\"frontend\", name!=\"\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}